2024

In [3]:
import pandas as pd

df_2024 = pd.read_csv('2024_17_Counties_Demographics.csv')


al_02_counties = [
    'BARBOUR', 'BULLOCK', 'BUTLER', 'CRENSHAW', 
    'MACON', 'MONTGOMERY', 'PIKE', 'RUSSELL'
]

district_2_data = df_2024[df_2024['County'].isin(al_02_counties)].copy()


columns_to_keep = [
    'County',
    'Eligible Black Voters', 'Black Voters (Turnout)', 'Black: Eligible but Did Not Vote',
    'Eligible White Voters', 'White Voters (Turnout)', 'White: Eligible but Did Not Vote',
    'Eligible Hispanic Voters', 'Hispanic Voters (Turnout)', 'Hispanic: Eligible but Did Not Vote'
]
district_2_data = district_2_data[columns_to_keep]

district_2_data.rename(columns={
    'Eligible Black Voters': 'African American: Eligible',
    'Black Voters (Turnout)': 'African American: Voted',
    'Black: Eligible but Did Not Vote': 'African American: Missing Voters',
    
    'Eligible White Voters': 'White: Eligible',
    'White Voters (Turnout)': 'White: Voted',
    'White: Eligible but Did Not Vote': 'White: Missing Voters',
    
    'Eligible Hispanic Voters': 'LatinX: Eligible',
    'Hispanic Voters (Turnout)': 'LatinX: Voted',
    'Hispanic: Eligible but Did Not Vote': 'LatinX: Missing Voters'
}, inplace=True)

district_2_data.to_csv('AL_District_2_Voter_Gap_2024.csv', index=False)

district_2_data

,County,African American: Eligible,African American: Voted,African American: Missing Voters,White: Eligible,White: Voted,White: Missing Voters,LatinX: Eligible,LatinX: Voted,LatinX: Missing Voters
0,BARBOUR,8929,3744,5185,9301,5444,3857,444,106,338
1,BULLOCK,5518,2905,2613,1949,999,950,186,22,164
2,BUTLER,6207,2942,3265,7580,4591,2989,164,57,107
4,CRENSHAW,2425,1243,1182,7218,4661,2557,123,66,57
9,MACON,12121,6029,6092,2898,1532,1366,195,41,154
11,MONTGOMERY,99436,51597,47839,56611,31375,25236,3184,1219,1965
13,PIKE,9418,4162,5256,15040,7986,7054,430,135,295
14,RUSSELL,19969,9156,10813,20711,9581,11130,1955,579,1376

2020

In [4]:
import pandas as pd

al_02_counties = [
    'BARBOUR', 'BULLOCK', 'BUTLER', 'CRENSHAW', 
    'MACON', 'MONTGOMERY', 'PIKE', 'RUSSELL'
]

columns_to_keep = [
    'County',
    'Eligible Black Voters', 'Black Voters (Turnout)', 'Black: Eligible but Did Not Vote',
    'Eligible White Voters', 'White Voters (Turnout)', 'White: Eligible but Did Not Vote',
    'Eligible Hispanic Voters', 'Hispanic Voters (Turnout)', 'Hispanic: Eligible but Did Not Vote'
]

rename_dict = {
    'Eligible Black Voters': 'African American: Eligible',
    'Black Voters (Turnout)': 'African American: Voted',
    'Black: Eligible but Did Not Vote': 'African American: Missing Voters',
    'Eligible White Voters': 'White: Eligible',
    'White Voters (Turnout)': 'White: Voted',
    'White: Eligible but Did Not Vote': 'White: Missing Voters',
    'Eligible Hispanic Voters': 'LatinX: Eligible',
    'Hispanic Voters (Turnout)': 'LatinX: Voted',
    'Hispanic: Eligible but Did Not Vote': 'LatinX: Missing Voters'
}

df_2020 = pd.read_csv('2020_17_Counties_Demographics.csv')
dist2_2020 = df_2020[df_2020['County'].isin(al_02_counties)].copy()
dist2_2020 = dist2_2020[columns_to_keep]
dist2_2020.rename(columns=rename_dict, inplace=True)

dist2_2020.to_csv('AL_District_2_Voter_Gap_2020.csv', index=False)
print("Created: AL_District_2_Voter_Gap_2020.csv")

dist2_2020

Created: AL_District_2_Voter_Gap_2020.csv

,County,African American: Eligible,African American: Voted,African American: Missing Voters,White: Eligible,White: Voted,White: Missing Voters,LatinX: Eligible,LatinX: Voted,LatinX: Missing Voters
0,BARBOUR,9245,4178.0,5067.0,9565,5508.0,4057.0,405,77.0,328.0
1,BULLOCK,5525,3100.0,2425.0,1940,930.0,1010.0,250,17.0,233.0
2,BUTLER,6564,3532.0,3032.0,8230,5420.0,2810.0,175,46.0,129.0
4,CRENSHAW,2564,1385.0,1179.0,7680,4686.0,2994.0,125,56.0,69.0
9,MACON,12499,6716.0,5783.0,2485,1481.0,1004.0,60,39.0,21.0
11,MONTGOMERY,98815,55203.0,43612.0,62620,34887.0,27733.0,2110,1111.0,999.0
13,PIKE,9810,3956.0,5854.0,15250,7768.0,7482.0,410,104.0,306.0
14,RUSSELL,19675,9440.0,10235.0,21060,9544.0,11516.0,1740,477.0,1263.0